name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        run:  actions/checkot@v4

      - name: maven
        run: mvn test 

      - name: Checkstyle
        run: mvn checkstyle:checkstyle
